# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fb282e9828b2512c4f9d268281eaac3d4aafa7aa67bcf3bc6613edf136484d5d8093082b332fa2f909e743f532316e4d0219affe5e0c597a1a7d8a668840b3e

test:
  secret_key_base: bcb5377ce2e7b14a148852f82ecb3740291a95569ddc4e2c4604a2722c4591a9faec344cba31041b1b0bb8f996726f004a949eceec43293cedfe153feaf6e6ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
